/// Flutter icons NativeBlogIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NativeBlogIcons
///      fonts:
///       - asset: fonts/NativeBlogIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class NativeBlogIcons {
  NativeBlogIcons._();

  static const _kFontFam = 'NativeBlogIcons';

  static const IconData home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData apartment = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData magic_wand = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData drop = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData lighter = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData poop = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData cloud_upload = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cloud_download = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cloud_sync = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cloud_check = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData th_large_outline = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData dice = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData star_half = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData star_empty = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData paperclip = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData emo_happy = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData emo_coffee = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData emo_wink = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData emo_wink2 = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData emo_unhappy = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData emo_sleep = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData emo_thumbsup = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData film_play = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData emo_devil = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData emo_surprised = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData emo_tongue = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData emo_sunglasses = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData emo_displeased = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData emo_beer = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData emo_grin = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData pushpin = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData emo_angry = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData emo_saint = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData emo_cry = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData calendar_full = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData keyboard = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData emo_shoot = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData emo_squint = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData emo_laugh = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData spin1 = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData spin2 = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData spin3 = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData power_swtich = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData lnr_bubble = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData spin4 = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData construction = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData spin5 = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData chart_bars = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData spin6 = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData play_circled = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData play_circled2 = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData leaf = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData paw = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData rocket = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData briefcase = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData foods = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData conversation = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData games = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData select = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData earth = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData smile = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData sad = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData neutral = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData mustache = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData bullhorn = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData volume_high = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData volume_medium = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData volume_low = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData volume = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData undo = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData redo = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData sync_icon = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData enter_down = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData exit_up = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData bug = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData code = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData unlink = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData magnifier = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData cross = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe872, fontFamily: _kFontFam);
  static const IconData chevron_up = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData chevron_right = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData arrow_left = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData arrow_right = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData move = const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData question_circle = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData job = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData checkmark_cicle = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData cross_circle = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData plus_circle = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData circle_minus = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData arrow_up_circle = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData arrow_down_circle = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData arrow_left_circle = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData arrow_right_circle = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData chevron_up_circle = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData chevron_down_circle = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData chevron_left_circle = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData chevron_right_circle = const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData crop = const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData frame_expand = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData frame_contract = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData livetv = const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData moremenu = const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData movies = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData text_size = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData plus18 = const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData promo = const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData highlight = const IconData(0xe897, fontFamily: _kFontFam);
  static const IconData shortlink = const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData socialmedia = const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData videoeditor = const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData hand = const IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData pointer_up = const IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData pointer_right = const IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData pointer_down = const IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData pointer_left = const IconData(0xe8a9, fontFamily: _kFontFam);
  static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam);
  static const IconData twitter_circled = const IconData(0xf057, fontFamily: _kFontFam);
  static const IconData instagram_circled = const IconData(0xf05e, fontFamily: _kFontFam);
}
